global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "saleor"
    static_configs:
      - targets: ["api:8000"]

  - job_name: 'redis'
    static_configs:
    - targets: ['redis_exporter:9121']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9808']

  - job_name: "node"
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:8888"]
